version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/presentations/2026-06-gpsl"
    schedule:
      interval: weekly
