# Jekyll configuration file

title: Patrick van Staveren
email: trick@vanstaveren.us
description: >-
  Just a few more bytes on the Internet.
baseurl: ""
url: "http://trick.vanstaveren.us"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-last-modified-at
#  - jekyll-feed

last-modified-at:
    git-authordate: True

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - push
  - build
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

