# Jekyll configuration file

title: Patrick van Staveren
email: trick@vanstaveren.us
description: >-
  Just a few more bytes on the Internet.
baseurl: ""
url: "http://trick.vanstaveren.us"
twitter_username: trickv
github_username:  trickv

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - push
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

