#!/usr/bin/env bash

if [ "$1" == "--real" ]; then
    echo "Pushing LIVE."
    flags=""
else
    flags="-n"
    echo "DRY RUN mode, specify --real to go"
fi

rsync -avc $flags --delete-after --exclude wp  _site/ root@hg.v9n.us:/var/www/trick.vanstaveren.us/
