#!/usr/bin/env bash

if [ "$1" == "--real" ]; then
    echo "Pushing LIVE."
    flags=""
else
    flags="-n"
    echo "DRY RUN mode, specify --real to go"
fi

rsync -rlpgoD -vc $flags --delete-after --exclude wp  _site/ root@hg.v9n.us:/var/www/trick.vanstaveren.us/

echo "If you have a long list of changes, remember to run:"
echo "    bundle exec jekyll build"
echo "before pushing so you don't accidentally push local dev headers live."
